name: Release pipeline

on:
  push:
    tags:
      - '*'

jobs:
  wechaty:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Set version
        run: |
          export GITHUB_TAG=${GITHUB_REF##*/}
          mvn versions:set -DnewVersion=$GITHUB_TAG
          sed -i 's/<tag>HEAD<\/tag>/<tag>$GITHUB_TAG<\/tag>/' pom.xml
      - name: Publish to the Maven Central Repository
        run: mvn deploy --batch-mode --activate-profiles deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

